In [55]:
#importing dependency
import pandas as pd
import pymysql
from sqlalchemy import create_engine

In [2]:
# loading the dataset
files = {
    "dc": "distribution_centers",
    "e": "events",
    "ii": "inventory_items",
    "oi": "order_items",
    "o": "orders",
    "p": "products",
    "u": "users",
}

for key, value in files.items():
    files[key] = pd.read_csv(f"../data/raw_data/{value}.csv")
    print(f"{value} dataset loaded successfully.")

distribution_centers dataset loaded successfully.
events dataset loaded successfully.
inventory_items dataset loaded successfully.
order_items dataset loaded successfully.
orders dataset loaded successfully.
products dataset loaded successfully.
users dataset loaded successfully.

In [3]:
#making global variables for the datasets
dc = files["dc"]
e = files["e"]
ii = files["ii"]
oi = files["oi"]
o = files["o"]
p = files["p"]
u = files["u"]

**Distribution Centers:**

In [4]:
dc.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10 non-null     int64
 1   name       10 non-null     str
 2   latitude   10 non-null     float64
 3   longitude  10 non-null     float64
dtypes: float64(2), int64(1), str(1)
memory usage: 452.0 bytes

In [5]:
dc.head(10)

   id                                         name  latitude  longitude
0   1                                   Memphis TN   35.1174   -89.9711
1   2                                   Chicago IL   41.8369   -87.6847
2   3                                   Houston TX   29.7604   -95.3698
3   4                               Los Angeles CA   34.0500  -118.2500
4   5                               New Orleans LA   29.9500   -90.0667
5   6  Port Authority of New York/New Jersey NY/NJ   40.6340   -73.7834
6   7                              Philadelphia PA   39.9500   -75.1667
7   8                                    Mobile AL   30.6944   -88.0431
8   9                                Charleston SC   32.7833   -79.9333
9  10                                  Savannah GA   32.0167   -81.1167

No issues in distribution centers table.

**Events:**

In [6]:
e.info()

<class 'pandas.DataFrame'>
RangeIndex: 2431963 entries, 0 to 2431962
Data columns (total 13 columns):
 #   Column           Dtype
---  ------           -----
 0   id               int64
 1   user_id          float64
 2   sequence_number  int64
 3   session_id       str
 4   created_at       str
 5   ip_address       str
 6   city             str
 7   state            str
 8   postal_code      str
 9   browser          str
 10  traffic_source   str
 11  uri              str
 12  event_type       str
dtypes: float64(1), int64(2), str(10)
memory usage: 241.2 MB

In [7]:
e.head()

,id,user_id,sequence_number,session_id,created_at,ip_address,city,state,postal_code,browser,traffic_source,uri,event_type
0,2198523,NaN,3,83889ed2-2adc-4b9a-af5d-154f6998e778,2021-06-17 17:30:00+00:00,138.143.9.202,São Paulo,São Paulo,02675-031,Chrome,Adwords,/cancel,cancel
1,1773216,NaN,3,7a3fc3f2-e84f-44fe-8876-eff76741f7a3,2020-08-07 08:41:00+00:00,85.114.141.79,Santa Isabel,São Paulo,07500-000,Safari,Adwords,/cancel,cancel
2,2380515,NaN,3,13d9b2fb-eee1-43fd-965c-267b38dd7125,2021-02-15 18:48:00+00:00,169.250.255.132,Mairiporã,São Paulo,07600-000,IE,Adwords,/cancel,cancel
3,2250597,NaN,3,96f1d44e-9621-463c-954c-d8deb7fffe7f,2022-03-30 10:56:00+00:00,137.25.222.160,Cajamar,São Paulo,07750-000,Chrome,Adwords,/cancel,cancel
4,1834446,NaN,3,d09dce10-a7cb-47d3-a9af-44975566fa03,2019-09-05 01:18:00+00:00,161.114.4.174,São Paulo,São Paulo,09581-680,Chrome,Email,/cancel,cancel

In [8]:
#deleting unnecessary columns from the events dataset
e.drop(columns=['ip_address', 'city', 'state', 'postal_code', 'uri'], inplace=True)

In [9]:
#null percentage in each column
e.isnull().sum() / len(e) * 100

id                  0.000000
user_id            46.286518
sequence_number     0.000000
session_id          0.000000
created_at          0.000000
browser             0.000000
traffic_source      0.000000
event_type          0.000000
dtype: float64

46% null values in user is id due to anonymous visits of users.

In [10]:
#checking the duplicates
e['id'].duplicated().sum()

np.int64(0)

No duplicates found.

In [11]:
#function to split created_at column into date and time
def split_date_time(df, column_name):
    df[column_name] = pd.to_datetime(df[column_name], format="ISO8601")
    df["date"] = df[column_name].dt.date
    df["time"] = df[column_name].dt.time
    df.drop(columns=[column_name], inplace=True)
    return df

In [12]:
#calling split_date_time function on events dataset
e = split_date_time(e, 'created_at')

In [13]:
# arranging the columns in a specific order
e = e[[
    "id",
    "event_type",
    "sequence_number",
    "user_id",
    "session_id",
    "date",
    "time",
    "browser",
    "traffic_source"
]]

In [14]:
e.head(3)

,id,event_type,sequence_number,user_id,session_id,date,time,browser,traffic_source
0,2198523,cancel,3,NaN,83889ed2-2adc-4b9a-af5d-154f6998e778,2021-06-17,17:30:00,Chrome,Adwords
1,1773216,cancel,3,NaN,7a3fc3f2-e84f-44fe-8876-eff76741f7a3,2020-08-07,08:41:00,Safari,Adwords
2,2380515,cancel,3,NaN,13d9b2fb-eee1-43fd-965c-267b38dd7125,2021-02-15,18:48:00,IE,Adwords

In [15]:
#checking inconsistencies in data
col_check=['event_type', 'sequence_number', 'browser', 'traffic_source']
for column in col_check:
    print(f"Unique values in {column}:")
    print(e[column].unique(), "\n")

Unique values in event_type:
<StringArray>
['cancel', 'cart', 'department', 'home', 'product', 'purchase']
Length: 6, dtype: str

Unique values in sequence_number:
[ 3  6  4  2  9 12  1 10  7 11  8  5 13]

Unique values in browser:
<StringArray>
['Chrome', 'Safari', 'IE', 'Other', 'Firefox']
Length: 5, dtype: str

Unique values in traffic_source:
<StringArray>
['Adwords', 'Email', 'Facebook', 'YouTube', 'Organic']
Length: 5, dtype: str

No inconsistencies found.

**Inventory Items:**

In [16]:
ii.info()

<class 'pandas.DataFrame'>
RangeIndex: 490705 entries, 0 to 490704
Data columns (total 12 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              490705 non-null  int64
 1   product_id                      490705 non-null  int64
 2   created_at                      490705 non-null  str
 3   sold_at                         181759 non-null  str
 4   cost                            490705 non-null  float64
 5   product_category                490705 non-null  str
 6   product_name                    490676 non-null  str
 7   product_brand                   490304 non-null  str
 8   product_retail_price            490705 non-null  float64
 9   product_department              490705 non-null  str
 10  product_sku                     490705 non-null  str
 11  product_distribution_center_id  490705 non-null  int64
dtypes: float64(2), int64(3), str(7)
memory usage: 44.9 MB

In [17]:
#keeping the relevant columns
ii = ii[["id", "product_id", "product_category", "product_retail_price", "cost"]]
ii.head(3)

      id  product_id product_category  product_retail_price     cost
0  67971       13844      Accessories                  6.99  2.76804
1  67972       13844      Accessories                  6.99  2.76804
2  67973       13844      Accessories                  6.99  2.76804

In [18]:
ii.info()

<class 'pandas.DataFrame'>
RangeIndex: 490705 entries, 0 to 490704
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    490705 non-null  int64
 1   product_id            490705 non-null  int64
 2   product_category      490705 non-null  str
 3   product_retail_price  490705 non-null  float64
 4   cost                  490705 non-null  float64
dtypes: float64(2), int64(2), str(1)
memory usage: 18.7 MB

No null values.

In [19]:
#checking the duplicates
ii['id'].duplicated().sum()

np.int64(0)

No Duplicate values.

In [20]:
#checking inconsistencies in product category column
ii['product_category'].unique()

<StringArray>
[                  'Accessories',                        'Active',
             'Blazers & Jackets',                 'Clothing Sets',
                       'Dresses', 'Fashion Hoodies & Sweatshirts',
                     'Intimates',                         'Jeans',
           'Jumpsuits & Rompers',                      'Leggings',
                     'Maternity',             'Outerwear & Coats',
                         'Pants',                'Pants & Capris',
                          'Plus',                        'Shorts',
                        'Skirts',                'Sleep & Lounge',
                         'Socks',               'Socks & Hosiery',
                         'Suits',           'Suits & Sport Coats',
                      'Sweaters',                          'Swim',
                   'Tops & Tees',                     'Underwear']
Length: 26, dtype: str

No inconsistencies found.

In [21]:
#rounding cost and product_retail_price columns to 2 decimal places
ii['cost'] = ii['cost'].round(2)
ii['product_retail_price'] = ii['product_retail_price'].round(2)
ii.head(2)

      id  product_id product_category  product_retail_price  cost
0  67971       13844      Accessories                  6.99  2.77
1  67972       13844      Accessories                  6.99  2.77

**Order Items:**

In [22]:
oi.info()

<class 'pandas.DataFrame'>
RangeIndex: 181759 entries, 0 to 181758
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 181759 non-null  int64
 1   order_id           181759 non-null  int64
 2   user_id            181759 non-null  int64
 3   product_id         181759 non-null  int64
 4   inventory_item_id  181759 non-null  int64
 5   status             181759 non-null  str
 6   created_at         181759 non-null  str
 7   shipped_at         118281 non-null  str
 8   delivered_at       63841 non-null   str
 9   returned_at        18232 non-null   str
 10  sale_price         181759 non-null  float64
dtypes: float64(1), int64(5), str(5)
memory usage: 15.3 MB

In [23]:
#removing unnecessary columns
oi = oi.drop(columns=['shipped_at', 'delivered_at', 'returned_at'])

In [24]:
#applying the split_date_time function to order_items dataset
oi = split_date_time(oi, 'created_at')

In [25]:
oi.columns

Index(['id', 'order_id', 'user_id', 'product_id', 'inventory_item_id',
       'status', 'sale_price', 'date', 'time'],
      dtype='str')

In [26]:
# aranging the columns in a specific order
oi = oi[
    [
        "id",
        "order_id",
        "user_id",
        "product_id",
        "inventory_item_id",
        "date",
        "time",
        "status",
        "sale_price",
    ]
]

In [27]:
oi.head(2)

,id,order_id,user_id,product_id,inventory_item_id,date,time,status,sale_price
0,152013,104663,83582,14235,410368,2023-05-07,06:08:40,Cancelled,0.02
1,40993,28204,22551,14235,110590,2023-03-14,03:47:21,Complete,0.02

In [28]:
#checking the duplicates
oi['id'].duplicated().sum()

np.int64(0)

No duplicates.

In [29]:
#checking inconsistencies in status column
oi['status'].unique()

<StringArray>
['Cancelled', 'Complete', 'Shipped', 'Processing', 'Returned']
Length: 5, dtype: str

No inconsistencies.

**Orders:**

In [30]:
o.info()

<class 'pandas.DataFrame'>
RangeIndex: 125226 entries, 0 to 125225
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      125226 non-null  int64
 1   user_id       125226 non-null  int64
 2   status        125226 non-null  str
 3   gender        125226 non-null  str
 4   created_at    125226 non-null  str
 5   returned_at   12530 non-null   str
 6   shipped_at    81461 non-null   str
 7   delivered_at  43884 non-null   str
 8   num_of_item   125226 non-null  int64
dtypes: int64(3), str(6)
memory usage: 8.6 MB

In [31]:
#removing unnecessary columns
o = o.drop(columns=['shipped_at', 'delivered_at', 'returned_at'])

In [32]:
#finding duplicates
o['order_id'].duplicated().sum()

np.int64(0)

No duplicates found.

In [33]:
#calling split_date_time function on orders dataset
o = split_date_time(o, 'created_at')

In [34]:
#checking for inconsistencies
col_check=['status', 'gender']
for column in col_check:
    print(f"Unique values in {column}:")
    print(o[column].unique(),'\n')

Unique values in status:
<StringArray>
['Cancelled', 'Complete', 'Processing', 'Returned', 'Shipped']
Length: 5, dtype: str

Unique values in gender:
<StringArray>
['F', 'M']
Length: 2, dtype: str

No inconsistencies.

In [35]:
o.columns

Index(['order_id', 'user_id', 'status', 'gender', 'num_of_item', 'date',
       'time'],
      dtype='str')

In [36]:
#aranging the columns in a specific order
o = o[['order_id', 'user_id', 'date', 'time', 'status', 'gender', 'num_of_item']]

**Products:**

In [37]:
p.info()

<class 'pandas.DataFrame'>
RangeIndex: 29120 entries, 0 to 29119
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      29120 non-null  int64
 1   cost                    29120 non-null  float64
 2   category                29120 non-null  str
 3   name                    29118 non-null  str
 4   brand                   29096 non-null  str
 5   retail_price            29120 non-null  float64
 6   department              29120 non-null  str
 7   sku                     29120 non-null  str
 8   distribution_center_id  29120 non-null  int64
dtypes: float64(2), int64(2), str(5)
memory usage: 2.0 MB

In [38]:
#removing unnecessary columns
p = p.drop(columns=['sku', 'distribution_center_id'])

In [39]:
#finding duplicates
p['id'].duplicated().sum()

np.int64(0)

No Duplicate values found.

In [40]:
p.head()

,id,cost,category,name,brand,retail_price,department
0,13842,2.51875,Accessories,Low Profile Dyed Cotton Twill Cap - Navy W39S55D,MG,6.25,Women
1,13928,2.33835,Accessories,Low Profile Dyed Cotton Twill Cap - Putty W39S55D,MG,5.95,Women
2,14115,4.87956,Accessories,Enzyme Regular Solid Army Caps-Black W35S45D,MG,10.99,Women
3,14157,4.64877,Accessories,Enzyme Regular Solid Army Caps-Olive W35S45D (...,MG,10.99,Women
4,14273,6.50793,Accessories,Washed Canvas Ivy Cap - Black W11S64C,MG,15.99,Women

In [41]:
#rounding cost and retail_price columns to 2 decimal places
p['cost'] = p['cost'].round(2)
p['retail_price'] = p['retail_price'].round(2)

**Users:**

In [42]:
u.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              100000 non-null  int64
 1   first_name      100000 non-null  str
 2   last_name       100000 non-null  str
 3   email           100000 non-null  str
 4   age             100000 non-null  int64
 5   gender          100000 non-null  str
 6   state           100000 non-null  str
 7   street_address  100000 non-null  str
 8   postal_code     100000 non-null  str
 9   city            99042 non-null   str
 10  country         100000 non-null  str
 11  latitude        100000 non-null  float64
 12  longitude       100000 non-null  float64
 13  traffic_source  100000 non-null  str
 14  created_at      100000 non-null  str
dtypes: float64(2), int64(2), str(11)
memory usage: 11.4 MB

In [43]:
#applying the split_date_time function to users dataset
u = split_date_time(u, 'created_at')

In [44]:
#keeping the relevant columns
u = u[['id', 'date', 'time', 'age', 'gender', 'country', 'city', 'traffic_source']]

In [45]:
#checking the duplicates
u['id'].duplicated().sum()

np.int64(0)

No duplicates.

In [46]:
#finding the percentage of null values in each column
u.isnull().sum() / len(p) * 100

id                0.000000
date              0.000000
time              0.000000
age               0.000000
gender            0.000000
country           0.000000
city              3.289835
traffic_source    0.000000
dtype: float64

In [47]:
#dropping the rows with null values in city column
u = u.dropna(subset=['city'])

In [48]:
u.reset_index(drop=True, inplace=True)

In [49]:
u.info()

<class 'pandas.DataFrame'>
RangeIndex: 99042 entries, 0 to 99041
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              99042 non-null  int64
 1   date            99042 non-null  object
 2   time            99042 non-null  object
 3   age             99042 non-null  int64
 4   gender          99042 non-null  str
 5   country         99042 non-null  str
 6   city            99042 non-null  str
 7   traffic_source  99042 non-null  str
dtypes: int64(2), object(2), str(4)
memory usage: 6.0+ MB

Cleaning completed.

In [50]:
#checking number of rows in each dataset
dfs={'dc': dc, 'e': e, 'ii': ii, 'oi': oi, 'o': o, 'p': p, 'u': u}
print("No. of rows in :")
for name, df in dfs.items():
    print(f"{name}: {df.shape[0]}")

No. of rows in :
dc: 10
e: 2431963
ii: 490705
oi: 181759
o: 125226
p: 29120
u: 99042

Since, number of valid rows in 'e' and 'ii' is too high, therefore, we will take samples of 'events' and 'inventory items' tables.

In [51]:
#building sets of valid user ids and product ids
valid_user_ids = set(u['id'])
valid_product_ids = set(p['id'])

In [52]:
#filtering events table with valid user ids and inventory items table with valid product ids
e = e[e['user_id'].isin(valid_user_ids) | e['user_id'].isnull()].reset_index(drop=True)
ii = ii[ii['product_id'].isin(valid_product_ids)].reset_index(drop=True)
print("Number of rows after filtering:")
print(f"Events: {e.shape[0]}")
print(f"Inventory Items: {ii.shape[0]}")

Number of rows after filtering:
Events: 2419787
Inventory Items: 490705

Invalid user ids were removed from the events table while inventory items contains all the valid product ids.

In [53]:
#taking the samples 
e=e.sample(n=300000, random_state=42).reset_index(drop=True)
ii=ii.sample(n=100000, random_state=42).reset_index(drop=True)

In [54]:
# #exporting the cleaned datasets to csv files
# dfs = {
#     "distribution_centers_clean": dc,
#     "events_clean": e,
#     "inventory_items_clean": ii,
#     'order_items_clean': oi,
#     'orders_clean': o,
#     'products_clean': p,
#     'users_clean': u
# }
# for name, df in dfs.items():
#     df.to_csv(f"../data/clean_data/{name}.csv", index=False)
#     print(f"{name} exported successfully.")

Exporting Data into MySQL database

In [56]:
#making connection
engine = create_engine('mysql+pymysql://root:root123@localhost:3306/thelook')

try:
    print("Connection to the database was successful!")
except:
    print("Failed to connect to the database.")

Connection to the database was successful!

In [58]:
tables = {
    "distribution_centers": dc,
    "events": e,
    "inventory_items": ii,
    "order_items": oi,
    "orders": o,
    "products": p,
    "users": u,
}

for table_name, df in tables.items():
    df.to_sql(table_name, con=engine, if_exists='replace', index=False)
    print(f"{table_name} table created successfully in the database.")

distribution_centers table created successfully in the database.
events table created successfully in the database.
inventory_items table created successfully in the database.
order_items table created successfully in the database.
orders table created successfully in the database.
products table created successfully in the database.
users table created successfully in the database.